
import { Channel } from './types';

// Detect if we are running on the eon.tv domain to use relative paths
const isNativeDomain = typeof window !== 'undefined' && window.location.hostname.endsWith('eon.tv');

export const CHANNELS: Channel[] = [
  { id: '82', name: 'БНТ 1 HD' },
  { id: '83', name: 'bTV HD' },
  { id: '84', name: 'Нова HD' },
  { id: '85', name: 'Nova News HD' },
  { id: '86', name: 'bTV Comedy HD' },
  { id: '87', name: 'bTV Cinema HD' },
  { id: '88', name: 'bTV Action HD' },
  { id: '331', name: 'Diema HD' },
  { id: '330', name: 'Kino Nova HD' },
  { id: '1', name: 'VIVACOM Arena HD' },
  { id: '329', name: 'Diema Family HD' },
  { id: '342', name: 'BulgariaOnAir HD' },
  { id: '326', name: 'dizi HD' },
  { id: '128', name: 'bTV Story HD' },
  { id: '386', name: 'Arena Action HD' },
  { id: '388', name: 'Arena Comedy HD' },
  { id: '387', name: 'Arena Life HD' },
  { id: '334', name: 'Euronews BG HD' },
  { id: '335', name: 'Евроком HD' },
  { id: '142', name: '7/8 TV HD' },
  { id: '346', name: 'БГ+ HD' },
  { id: '305', name: 'TV 1 HD' },
  { id: '332', name: 'БНТ 2 HD' },
  { id: '343', name: 'БНТ 4 HD' },
  { id: '91', name: 'STAR Channel HD' },
  { id: '129', name: 'STAR Life HD' },
  { id: '130', name: 'STAR Crime HD' },
  { id: '355', name: 'CineStar 1 HD' },
  { id: '356', name: 'CineStar A&T HD' },
  { id: '140', name: 'Epic Drama HD' },
  { id: '394', name: 'SkyShowtime 1 HD' },
  { id: '395', name: 'SkyShowtime 2 HD' },
  { id: '152', name: 'MovieStar HD' },
  { id: '339', name: 'FilmBOX Stars HD' },
  { id: '145', name: 'Filmbox Extra HD' },
  { id: '146', name: 'ArtHouse HD' },
  { id: '303', name: 'Cinemania HD' },
  { id: '304', name: 'Nostalgia HD' },
  { id: '390', name: 'Канал 4 HD' },
  { id: '151', name: 'TV 999 HD' },
  { id: '135', name: 'HBO HD' },
  { id: '136', name: 'HBO 2 HD' },
  { id: '137', name: 'HBO 3 HD' },
  { id: '138', name: 'Cinemax HD' },
  { id: '139', name: 'Cinemax 2 HD' },
  { id: '108', name: 'Nova Sport HD' },
  { id: '114', name: 'Diema Sport HD' },
  { id: '115', name: 'Diema Sport 2 HD' },
  { id: '285', name: 'Diema Sport 3 HD' },
  { id: '359', name: 'FightKlub HD' },
  { id: '101', name: 'Eurosport 1 HD' },
  { id: '102', name: 'Eurosport 2 HD' },
  { id: '103', name: 'MAX Sport 1 HD' },
  { id: '104', name: 'MAX Sport 2 HD' },
  { id: '105', name: 'MAX Sport 3 HD' },
  { id: '106', name: 'MAX Sport 4 HD' },
  { id: '110', name: 'БНТ 3 HD' },
  { id: '107', name: 'Ring HD' },
  { id: '111', name: 'FightBox HD' },
  { id: '380', name: 'ММА TV HD' },
  { id: '118', name: 'Fast and Fun HD' },
  { id: '117', name: 'AutoMotor' },
  { id: '121', name: 'Motorvision' },
  { id: '119', name: 'Fuel TV HD' },
  { id: '122', name: 'Gametoon HD' },
  { id: '347', name: 'SuperToons HD' },
  { id: '228', name: 'IDJ Kids HD' },
  { id: '344', name: 'Duck TV HD' },
  { id: '168', name: 'English Club' },
  { id: '369', name: 'Kids Stars HD' },
  { id: '254', name: 'Nat Geo HD' },
  { id: '253', name: 'Discovery HD' },
  { id: '262', name: 'History HD' },
  { id: '341', name: 'ViasatHistory HD' },
  { id: '340', name: 'ViasatExplore HD' },
  { id: '396', name: 'Love Nature HD' },
  { id: '256', name: 'Animal Planet HD' },
  { id: '333', name: 'Viasat Nature HD' },
  { id: '255', name: 'NG Wild HD' },
  { id: '379', name: 'V True Crime HD' },
  { id: '263', name: 'ID HD' },
  { id: '266', name: 'Docubox HD' },
  { id: '365', name: 'ЛРК HD' },
  { id: '126', name: 'FishingHunting' },
  { id: '131', name: '24 Kitchen HD' },
  { id: '392', name: 'Mate Kitchen HD' },
  { id: '296', name: 'Soul&Pepper HD' },
  { id: '368', name: 'Kitchen TV HD' },
  { id: '132', name: 'Food Network HD' },
  { id: '338', name: 'TLC HD' },
  { id: '267', name: 'Fashion TV HD' },
  { id: '268', name: 'Code Fashion TV' },
  { id: '270', name: 'FashionBox HD' },
  { id: '367', name: 'Travel XP HD' },
  { id: '393', name: 'Без багаж HD' },
  { id: '301', name: 'TV Tourism HD' },
  { id: '273', name: 'Travel Channel' },
  { id: '271', name: 'Wness HD' },
  { id: '283', name: 'Code Health TV' },
  { id: '219', name: 'Планета HD' },
  { id: '221', name: 'ФЕН ТВ HD' },
  { id: '225', name: 'Grand HD' },
  { id: '348', name: 'Hit Mix HD' },
  { id: '223', name: 'DSTV HD' },
  { id: '226', name: 'Grand 2 HD' },
  { id: '337', name: 'Балканика HD' },
  { id: '389', name: 'Тянков Ориент HD' },
  { id: '349', name: 'Планета Фолк HD' },
  { id: '235', name: 'The Voice HD' },
  { id: '236', name: 'Magic TV HD' },
  { id: '227', name: 'IDJ' },
  { id: '336', name: 'City TV HD' },
  { id: '350', name: 'BOX TV HD' },
  { id: '345', name: 'BG Music Ch. HD' },
  { id: '251', name: '360 TuneBox HD' },
  { id: '249', name: 'Deluxe Music HD' },
  { id: '250', name: 'Deluxe Lounge HD' },
  { id: '385', name: 'Oh!Jazz HD' },
  { id: '364', name: 'Marquee TV HD' },
  { id: '245', name: 'MTV Live' },
  { id: '252', name: 'iConcerts HD' },
  { id: '180', name: 'Euronews HD' },
  { id: '323', name: 'DomKino Premium' },
  { id: '377', name: 'beIN IZ HD' },
  { id: '378', name: 'beIN GURME HD' },
  { id: '353', name: 'TVE HD' },
  { id: '302', name: 'Nasha TV HD' },
  { id: '376', name: 'ТВ Шумен HD' },
  { id: '300', name: 'PPTV HD' },
  { id: '6', name: 'Dorcel TV HD' },
  { id: '5', name: 'REDLIGHT HD' },
  { id: '4', name: 'Playboy HD' },
  { id: '3', name: 'EROXXX HD' },
  { id: '2', name: 'XY Mix HD' },
  { id: '71', name: 'EroX HD' },
  { id: '286', name: 'EROTA HD' },
  { id: '374', name: 'Pinko Club HD' },
  { id: '375', name: 'CentoXCento HD' }
];

export const DEFAULT_CHANNEL_ID = '82';

// If on eon.tv, use relative path. Otherwise, use full URL.
export const PLAYER_BASE_URL = isNativeDomain ? '/player/' : 'https://eon.tv/player/';
export const IS_NATIVE_DOMAIN = isNativeDomain;
